name: Nifty Notification

on:
  schedule:
    - cron: "0 3 * * 1-5" # 8:30 AM IST (3:00 UTC)
  workflow_dispatch: # Allow manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: pip install beautifulsoup4 requests

    - name: Run Nifty Script
      env:
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python nifty-checker.py
